// <auto-generated/>
#pragma warning disable CS0618
using LocalTrader.Client.Api.Collections.Cards;
using LocalTrader.Client.Api.Collections.Magic;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LocalTrader.Client.Api.Collections
{
    /// <summary>
    /// Builds and executes requests for operations under \api\collections
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CollectionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cards property</summary>
        public global::LocalTrader.Client.Api.Collections.Cards.CardsRequestBuilder Cards
        {
            get => new global::LocalTrader.Client.Api.Collections.Cards.CardsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The magic property</summary>
        public global::LocalTrader.Client.Api.Collections.Magic.MagicRequestBuilder Magic
        {
            get => new global::LocalTrader.Client.Api.Collections.Magic.MagicRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalTrader.Client.Api.Collections.CollectionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CollectionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/collections", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalTrader.Client.Api.Collections.CollectionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CollectionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/collections", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
