using ScryfallApi.Client.Models;

namespace ScryfallApi.Client.Apis;

///<inheritdoc cref="IBulkData"/>
public class BulkData : IBulkData
{
    private readonly BaseRestService _restService;

    internal BulkData(BaseRestService restService)
    {
        _restService = restService;
    }

    public Task<ScryfallResult<ResultList<BulkDataItem>>> Get() => _restService.GetAsync<ResultList<BulkDataItem>>("/bulk-data", false);

    public async Task<ScryfallResult<List<BulkDataItem>>> Get(DateTimeOffset updatedSince)
    {
        var bulkData = await Get();
        return bulkData.Bind(x =>  x.Data.Where(d => d.LastUpdated >= updatedSince).ToList());
    }

    public async Task<ScryfallResult<BulkDataItem>> Get(DateTimeOffset updatedSince, string bulkDataType)
    {
        var updateData = (await Get(updatedSince))
            .Bind(x => x.FirstOrDefault(d => d.Type.Equals(bulkDataType, StringComparison.OrdinalIgnoreCase)));

        return updateData.Value is not null
            ? updateData.Bind(x => x!) // A hack to tell the compiler that the value is not null
            : new Error()
            {
                Code = "404",
                Details = $"No bulk data found for {bulkDataType}. This error is not directly generated by Scryfall.",
                ObjectType = "Error"
            };
    }

    public static class Types
    {
        /// <summary>
        /// A JSON file containing one Scryfall card object for each Oracle ID on Scryfall. The 
        /// chosen sets for the cards are an attempt to return the most up-to-date recognizable 
        /// version of the card.
        /// </summary>
        public static string OracleCards  => "oracle_cards";

        /// <summary>
        /// A JSON file of Scryfall card objects that together contain all unique artworks. The 
        /// chosen cards promote the best image scans.
        /// </summary>
        public static string UniqueArtwork  => "unique_artwork";

        /// <summary>
        /// A JSON file containing every card object on Scryfall in English or the printed 
        /// language if the card is only available in one language.
        /// </summary>
        public static string DefaultCards => "default_cards";

        /// <summary>
        /// A JSON file containing every card object on Scryfall in every language.
        /// </summary>
        public static string AllCards  => "all_cards";

        /// <summary>
        /// A JSON file containing all Rulings on Scryfall. Each ruling refers to cards via an `oracle_id`.
        /// </summary>
        public static string Rulings => "rulings";
    }
}
