// <auto-generated/>
#pragma warning disable CS0618
using LocalTrader.Client.Account.Logout;
using LocalTrader.Client.Account.Manage;
using LocalTrader.Client.Account.PasskeyCreationOptions;
using LocalTrader.Client.Account.PasskeyRequestOptions;
using LocalTrader.Client.Account.PerformExternalLogin;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LocalTrader.Client.Account
{
    /// <summary>
    /// Builds and executes requests for operations under \Account
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The Logout property</summary>
        public global::LocalTrader.Client.Account.Logout.LogoutRequestBuilder Logout
        {
            get => new global::LocalTrader.Client.Account.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Manage property</summary>
        public global::LocalTrader.Client.Account.Manage.ManageRequestBuilder Manage
        {
            get => new global::LocalTrader.Client.Account.Manage.ManageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The PasskeyCreationOptions property</summary>
        public global::LocalTrader.Client.Account.PasskeyCreationOptions.PasskeyCreationOptionsRequestBuilder PasskeyCreationOptions
        {
            get => new global::LocalTrader.Client.Account.PasskeyCreationOptions.PasskeyCreationOptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The PasskeyRequestOptions property</summary>
        public global::LocalTrader.Client.Account.PasskeyRequestOptions.PasskeyRequestOptionsRequestBuilder PasskeyRequestOptions
        {
            get => new global::LocalTrader.Client.Account.PasskeyRequestOptions.PasskeyRequestOptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The PerformExternalLogin property</summary>
        public global::LocalTrader.Client.Account.PerformExternalLogin.PerformExternalLoginRequestBuilder PerformExternalLogin
        {
            get => new global::LocalTrader.Client.Account.PerformExternalLogin.PerformExternalLoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalTrader.Client.Account.AccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Account", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalTrader.Client.Account.AccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Account", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
