using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;


namespace LocalTrader.Generators;

/// <summary>
/// A sample source generator that creates a custom report based on class properties. The target class should be annotated with the 'Generators.ReportAttribute' attribute.
/// When using the source code as a baseline, an incremental source generator is preferable because it reduces the performance overhead.
/// </summary>
[Generator]
public class SourceGeneratorWithAttributes : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {

        var provider = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(
                "StronglyTypedIds.StronglyTypedIdAttribute",
                Filter, (syntaxContext, _) => syntaxContext)
                .Collect();


        context.RegisterSourceOutput(provider, GenerateCode);
    }

    private static void GenerateCode(SourceProductionContext context, ImmutableArray<GeneratorAttributeSyntaxContext> generatorAttributeSyntaxContexts)
    {

        //configurationBuilder.Properties<UserId>().HaveConversion<UserId.EfCoreValueConverter>();
        var classNames = generatorAttributeSyntaxContexts
            .Select(x => x.TargetSymbol)
            .OfType<INamedTypeSymbol>()
            .Select(x => $"builder.Properties<{x.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>().HaveConversion<{x.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}.EfCoreValueConverter>();");

        var assemblyName = generatorAttributeSyntaxContexts
            .First()
            .TargetSymbol
            .ContainingAssembly
            .Name
            .Replace(".", "");
        var source = $$"""
                       // <auto-generated/>
                       namespace LocalTrader.Generated;

                       public static partial class  ConfigureConventionsExtensions
                       {
                           extension(global::Microsoft.EntityFrameworkCore.ModelConfigurationBuilder builder)
                           {
                               public void Register{{assemblyName}}StronglyTypedIds()
                               {
                                   {{string.Join("\n", classNames)}}
                               }
                           }
                       }
                       """;
        
        context.AddSource("ConfigureConventionsExtensions.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static bool Filter(SyntaxNode arg1, CancellationToken arg2)
    {
        return arg1 is StructDeclarationSyntax;
    }
}