// <auto-generated/>
#pragma warning disable CS0618
using LocalTrader.Client.Api.Collections.Magic.Cards;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LocalTrader.Client.Api.Collections.Magic
{
    /// <summary>
    /// Builds and executes requests for operations under \api\collections\magic
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MagicRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cards property</summary>
        public global::LocalTrader.Client.Api.Collections.Magic.Cards.CardsRequestBuilder Cards
        {
            get => new global::LocalTrader.Client.Api.Collections.Magic.Cards.CardsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalTrader.Client.Api.Collections.Magic.MagicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MagicRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/collections/magic", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalTrader.Client.Api.Collections.Magic.MagicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MagicRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/collections/magic", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
