// <auto-generated/>
#pragma warning disable CS0618
using LocalTrader.Client.Api.Collections;
using LocalTrader.Client.Api.Test;
using LocalTrader.Client.Api.WantLists;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LocalTrader.Client.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The collections property</summary>
        public global::LocalTrader.Client.Api.Collections.CollectionsRequestBuilder Collections
        {
            get => new global::LocalTrader.Client.Api.Collections.CollectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Test property</summary>
        public global::LocalTrader.Client.Api.Test.TestRequestBuilder Test
        {
            get => new global::LocalTrader.Client.Api.Test.TestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wantLists property</summary>
        public global::LocalTrader.Client.Api.WantLists.WantListsRequestBuilder WantLists
        {
            get => new global::LocalTrader.Client.Api.WantLists.WantListsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalTrader.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalTrader.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
