// <auto-generated/>
#pragma warning disable CS0618
using LocalTrader.Client.Api.Collections.Cards.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace LocalTrader.Client.Api.Collections.Cards
{
    /// <summary>
    /// Builds and executes requests for operations under \api\collections\cards
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CardsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the LocalTrader.Client.api.collections.cards.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::LocalTrader.Client.Api.Collections.Cards.Item.WithCardItemRequestBuilder"/></returns>
        public global::LocalTrader.Client.Api.Collections.Cards.Item.WithCardItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("cardId", position);
                return new global::LocalTrader.Client.Api.Collections.Cards.Item.WithCardItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalTrader.Client.Api.Collections.Cards.CardsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CardsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/collections/cards", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::LocalTrader.Client.Api.Collections.Cards.CardsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CardsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/collections/cards", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
